"use client";
import { useEffect, useMemo, useState } from "react";
import { Bell, CalendarDays, Check, ChevronLeft, ChevronRight, Circle, Command, LayoutDashboard, ListTodo, MoreHorizontal, Plus, Search, Settings, Sparkles, Target, TrendingUp, X } from "lucide-react";

type Priority = "HIGH" | "MEDIUM" | "LOW";
type Task = { id: string; title: string; description?: string; priority: Priority; category: string; dueDate: string; dueTime?: string; completed: boolean; createdAt: string; completedAt?: string };
const seed: Task[] = [
 {id:"1",title:"Complete interface calibration",description:"Refine dashboard states and loading behaviour.",priority:"HIGH",category:"Development",dueDate:new Date().toISOString().slice(0,10),dueTime:"10:30",completed:false,createdAt:new Date().toISOString()},
 {id:"2",title:"Review quarterly objectives",description:"Confirm priorities for the next sprint.",priority:"MEDIUM",category:"Work",dueDate:new Date().toISOString().slice(0,10),dueTime:"14:00",completed:false,createdAt:new Date().toISOString()},
 {id:"3",title:"Study system design",description:"Focus on distributed caching patterns.",priority:"LOW",category:"Study",dueDate:new Date(Date.now()+86400000).toISOString().slice(0,10),dueTime:"19:00",completed:false,createdAt:new Date().toISOString()},
 {id:"4",title:"Prepare weekly review",description:"Wins, blockers and next actions.",priority:"MEDIUM",category:"Personal",dueDate:new Date().toISOString().slice(0,10),completed:true,createdAt:new Date().toISOString(),completedAt:new Date().toISOString()}
];
const today = new Date().toISOString().slice(0,10);
function priorityRank(p: Priority) { return p === "HIGH" ? 0 : p === "MEDIUM" ? 1 : 2; }
export default function Home() {
 const [tasks,setTasks]=useState<Task[]>(seed), [modal,setModal]=useState(false), [query,setQuery]=useState(""), [filter,setFilter]=useState("TODAY"), [active,setActive]=useState("Dashboard"), [selected,setSelected]=useState<Task|null>(null), [toast,setToast]=useState("");
 const [form,setForm]=useState({title:"",description:"",priority:"MEDIUM" as Priority,category:"Work",dueDate:today,dueTime:""});
 useEffect(()=>{const saved=localStorage.getItem("apex-tasks"); if(saved) setTasks(JSON.parse(saved));},[]);
 useEffect(()=>localStorage.setItem("apex-tasks",JSON.stringify(tasks)),[tasks]);
 const visible=useMemo(()=>tasks.filter(t=>{ const text=`${t.title} ${t.description} ${t.category} ${t.priority}`.toLowerCase(); const matches=text.includes(query.toLowerCase()); const overdue=!t.completed && t.dueDate<today; const kind=filter==="ALL"||filter==="TODAY"&&t.dueDate===today||filter==="UPCOMING"&&t.dueDate>today||filter==="COMPLETED"&&t.completed||filter==="OVERDUE"&&overdue; return matches&&kind; }).sort((a,b)=>Number(a.completed)-Number(b.completed)||priorityRank(a.priority)-priorityRank(b.priority)),[tasks,query,filter]);
 const done=tasks.filter(t=>t.completed).length, overdue=tasks.filter(t=>!t.completed&&t.dueDate<today).length, pct=tasks.length?Math.round(done/tasks.length*100):0;
 const flash=(m:string)=>{setToast(m); setTimeout(()=>setToast(""),2600)};
 const toggle=(id:string)=>{setTasks(x=>x.map(t=>t.id===id?{...t,completed:!t.completed,completedAt:!t.completed?new Date().toISOString():undefined}:t)); flash("Task status updated");};
 const create=()=>{if(!form.title.trim()) return flash("A task title is required"); setTasks(x=>[{...form,id:crypto.randomUUID(),completed:false,createdAt:new Date().toISOString()},...x]); setForm({title:"",description:"",priority:"MEDIUM",category:"Work",dueDate:today,dueTime:""});setModal(false);flash("Task created");};
 const remove=(id:string)=>{setTasks(x=>x.filter(t=>t.id!==id));setSelected(null);flash("Task deleted");};
 const nav=[LayoutDashboard,ListTodo,Target,CalendarDays,TrendingUp,Check,Settings];
 const labels=["Dashboard","Tasks","Today","Calendar","Analytics","Completed","Settings"];
 return <main><aside><div className="brand"><span className="roundel"><i/></span><span>APEX <b>DRIVE</b></span></div><div className="rail">{labels.map((label,i)=>{const Icon=nav[i];return <button onClick={()=>{setActive(label); if(label==="Today")setFilter("TODAY"); if(label==="Completed")setFilter("COMPLETED")}} className={active===label?"nav active":"nav"} key={label}><Icon size={18}/><span>{label}</span></button>})}</div><div className="drive"><span className="dot"/> SYSTEMS NOMINAL</div><div className="profile"><div className="avatar">K</div><div><strong>Kartik Sharma</strong><small>Performance mode</small></div><MoreHorizontal size={18}/></div></aside>
 <section className="content"><header><div className="crumb"><span>Control Centre</span><b> / {active}</b></div><div className="tools"><button className="icon"><Search size={18}/></button><button className="icon"><Bell size={18}/><em/></button><button className="date"><CalendarDays size={16}/> {new Intl.DateTimeFormat("en",{month:"short",day:"numeric"}).format(new Date())}</button></div></header>
 <div className="hero"><div><p className="eyebrow">MONDAY · OCTOBER 05</p><h1>Good evening, Kartik<span>.</span></h1><p className="sub">Your next move is already in view. Make it precise.</p></div><button className="add" onClick={()=>setModal(true)}><Plus size={18}/> Add task <kbd>⌘ N</kbd></button></div>
 <div className="metrics"><Metric label="TODAY'S PROGRESS" value={`${done} / ${tasks.length}`} detail={`${pct}% complete`} pct={pct}/><Metric label="ACTIVE TASKS" value={String(tasks.length-done)} detail="Across all projects" icon={<Target size={19}/>}/><Metric label="ON SCHEDULE" value={overdue?`${overdue} overdue`:"All clear"} detail={overdue?"Needs attention":"No missed deadlines"} icon={<TrendingUp size={19}/>}/></div>
 <div className="layout"><div className="work"><div className="section-title"><div><p className="eyebrow">TASK QUEUE</p><h2>Today&apos;s focus</h2></div><button className="ghost" onClick={()=>setFilter(filter==="ALL"?"TODAY":"ALL")}>{filter==="ALL"?"Today":"View all"} <ChevronRight size={16}/></button></div><div className="filters"><Search size={16}/><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Search your tasks"/><div className="pills">{["ALL","TODAY","UPCOMING","COMPLETED","OVERDUE"].map(x=><button className={filter===x?"on":""} onClick={()=>setFilter(x)} key={x}>{x[0]+x.slice(1).toLowerCase()}</button>)}</div></div><div className="tasks">{visible.length?visible.map(t=><TaskRow key={t.id} task={t} toggle={toggle} open={()=>setSelected(t)}/>):<div className="empty"><Sparkles/><b>Nothing in this lane</b><span>Set a new objective when you&apos;re ready.</span><button onClick={()=>setModal(true)}>Add task</button></div>}</div></div>
 <div className="right"><div className="panel deadlines"><div className="panel-head"><h3>UPCOMING DEADLINES</h3><button onClick={()=>setFilter("UPCOMING")}>View</button></div>{tasks.filter(t=>!t.completed&&t.dueDate>=today).slice(0,3).map(t=><div className="deadline" key={t.id}><span className={`line ${t.priority.toLowerCase()}`}/><div><b>{t.title}</b><small>{t.dueDate===today?"Today":new Date(t.dueDate+"T12:00").toLocaleDateString("en",{weekday:"short",month:"short",day:"numeric"})} {t.dueTime&&`· ${t.dueTime}`}</small></div></div>)}</div><div className="panel calendar"><div className="cal-head"><ChevronLeft size={17}/><b>October 2026</b><ChevronRight size={17}/></div><div className="week">{["M","T","W","T","F","S","S"].map((d,i)=><span key={d+i}>{d}</span>)}</div><div className="days">{Array.from({length:31},(_,i)=><span className={i===4?"today":""} key={i}>{i+1}{[4,7,12].includes(i)&&<i/>}</span>)}</div></div><div className="panel activity"><div className="panel-head"><h3>RECENT ACTIVITY</h3></div><p><span className="activity-dot"/> System ready. Your workspace is synced.</p><p><span className="activity-dot blue"/> {done} completed task{done===1?"":"s"} recorded.</p></div></div></div></section>
 {modal&&<div className="overlay" onMouseDown={()=>setModal(false)}><div className="modal" onMouseDown={e=>e.stopPropagation()}><div className="modal-head"><div><p className="eyebrow">NEW OBJECTIVE</p><h2>Create task</h2></div><button className="icon" onClick={()=>setModal(false)}><X size={18}/></button></div><label>Task title<input autoFocus value={form.title} onChange={e=>setForm({...form,title:e.target.value})} placeholder="What needs your attention?"/></label><label>Description<textarea value={form.description} onChange={e=>setForm({...form,description:e.target.value})} placeholder="Add context (optional)"/></label><div className="field-row"><label>Priority<select value={form.priority} onChange={e=>setForm({...form,priority:e.target.value as Priority})}><option>HIGH</option><option>MEDIUM</option><option>LOW</option></select></label><label>Category<select value={form.category} onChange={e=>setForm({...form,category:e.target.value})}>{["Work","Personal","Study","Development","Other"].map(x=><option key={x}>{x}</option>)}</select></label></div><div className="field-row"><label>Due date<input type="date" value={form.dueDate} onChange={e=>setForm({...form,dueDate:e.target.value})}/></label><label>Time<input type="time" value={form.dueTime} onChange={e=>setForm({...form,dueTime:e.target.value})}/></label></div><div className="actions"><button className="cancel" onClick={()=>setModal(false)}>Cancel</button><button className="add" onClick={create}><Plus size={17}/> Create task</button></div></div></div>}
 {selected&&<div className="overlay" onMouseDown={()=>setSelected(null)}><div className="modal details" onMouseDown={e=>e.stopPropagation()}><div className="modal-head"><div><p className="eyebrow">TASK DETAIL</p><h2>{selected.title}</h2></div><button className="icon" onClick={()=>setSelected(null)}><X size={18}/></button></div><p className="detail-copy">{selected.description||"No supporting notes for this task."}</p><div className="detail-grid"><span>Priority <b className={selected.priority.toLowerCase()}>{selected.priority}</b></span><span>Category <b>{selected.category}</b></span><span>Due <b>{selected.dueDate} {selected.dueTime}</b></span><span>Status <b>{selected.completed?"Completed":"In progress"}</b></span></div><div className="actions"><button className="danger" onClick={()=>remove(selected.id)}>Delete task</button><button className="add" onClick={()=>{toggle(selected.id);setSelected(null)}}>{selected.completed?"Mark active":"Complete task"}</button></div></div></div>}
 {toast&&<div className="toast"><Check size={16}/>{toast}</div>}</main>;
}
function Metric({label,value,detail,pct,icon}:{label:string,value:string,detail:string,pct?:number,icon?:React.ReactNode}){return <div className="metric"><div className="metric-top"><span>{label}</span>{icon}</div><div className="metric-value">{value}</div><div className="metric-detail">{pct!==undefined&&<span className="bar"><i style={{width:`${pct}%`}}/></span>}{detail}</div></div>}
function TaskRow({task,toggle,open}:{task:Task;toggle:(id:string)=>void;open:()=>void}){return <article className={`task ${task.completed?"complete":""}`}><button className="check" aria-label="Toggle completion" onClick={()=>toggle(task.id)}>{task.completed&&<Check size={14}/>}</button><button className="task-main" onClick={open}><span className="task-title">{task.title}</span><span className="task-desc">{task.description||"No description"}</span></button><span className={`priority ${task.priority.toLowerCase()}`}>{task.priority}</span><span className="task-time">{task.dueTime||"—"}</span><button className="more" onClick={open}><MoreHorizontal size={18}/></button></article>}
